// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDixiYjrG6L3zYHih9V-Gdnw84tcNHnbxw',
    appId: '1:213670417610:web:8f7ac2aadabdde8ac69033',
    messagingSenderId: '213670417610',
    projectId: 'inno-test-2a383',
    authDomain: 'inno-test-2a383.firebaseapp.com',
    storageBucket: 'inno-test-2a383.appspot.com',
    measurementId: 'G-8R9G8EDZC2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATvp4aFkHiiRYh9398hKI9P5hIkSeuhNg',
    appId: '1:213670417610:android:0b4f6c4a1e407446c69033',
    messagingSenderId: '213670417610',
    projectId: 'inno-test-2a383',
    storageBucket: 'inno-test-2a383.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLu6qTnvpxHCMYyMhbLQmlUdWDXn99rM4',
    appId: '1:213670417610:ios:6186a10912d1cdedc69033',
    messagingSenderId: '213670417610',
    projectId: 'inno-test-2a383',
    storageBucket: 'inno-test-2a383.appspot.com',
    iosBundleId: 'com.example.innotest.innotest',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLu6qTnvpxHCMYyMhbLQmlUdWDXn99rM4',
    appId: '1:213670417610:ios:6186a10912d1cdedc69033',
    messagingSenderId: '213670417610',
    projectId: 'inno-test-2a383',
    storageBucket: 'inno-test-2a383.appspot.com',
    iosBundleId: 'com.example.innotest.innotest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDixiYjrG6L3zYHih9V-Gdnw84tcNHnbxw',
    appId: '1:213670417610:web:49188f92adca87ffc69033',
    messagingSenderId: '213670417610',
    projectId: 'inno-test-2a383',
    authDomain: 'inno-test-2a383.firebaseapp.com',
    storageBucket: 'inno-test-2a383.appspot.com',
    measurementId: 'G-J2G5RDT4KB',
  );

}